# Generated by Django 4.0 on 2022-01-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='music',
        ),
        migrations.RemoveField(
            model_name='music',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
